Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Print_Multiples1.py =============
7
14
21
28
35
42
49
56
63
70
77
84
91
98
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Print_Multiples2.py =============
7
14
21
28
35
42
49
56
63
70
77
84
91
98
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Print_Multiples3.py =============
7
14
21
28
35
42
49
56
63
70
77
84
91
98
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
4
Traceback (most recent call last):
  File "C:/Python371/MyP/Ch2_Decimal_To_Binary.py", line 6, in <module>
    converted=rem+converted
NameError: name 'converted' is not defined
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
4
100
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
32
100000
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
2
10
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
2
01
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
64
1000000
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
23
10111
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
7
111
>>> 
============= RESTART: C:/Python371/MyP/Ch2_Decimal_To_Binary.py =============
Enter number in decimal
1
1
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
[123, 234, 345, 456, 0, 0]
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
Traceback (most recent call last):
  File "C:/Python371/MyP/Ch2_Arrays.py", line 2, in <module>
    print(runs(1))
TypeError: 'list' object is not callable
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
234
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
123
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
0
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
[123, 234, 345, 456, 0, 0]
>>> 
================== RESTART: C:/Python371/MyP/Ch2_Arrays.py ==================
[123, 234, 345, 456, 0, 0]
123
0
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
[4, 343, 'Dixit', 'Sharma']
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
347
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
Traceback (most recent call last):
  File "C:/Python371/MyP/Ch2_Arrays_Append.py", line 3, in <module>
    print(runs[0]+runs[1]+runs[2])
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
21
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
[4, 343, 'Dixit', 'Sharma', 21]
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
[4, 343, 'Dixit', 'Sharma', 21]
[4, 343, 42, 'Dixit', 'Sharma', 21]
>>> 
=============== RESTART: C:/Python371/MyP/Ch2_Arrays_Append.py ===============
[4, 343, 'Dixit', 'Sharma', 21]
[4, 343, 42, 'Dixit', 'Sharma', 21]
>>> 
=========== RESTART: C:/Python371/MyP/Ch2_Arrays_Delete_Remove.py ===========
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 4, 5, 6, 7, 8]
>>> 
=========== RESTART: C:/Python371/MyP/Ch2_Arrays_Delete_Remove.py ===========
[1, 2, 3, 4, 5, 6, 7, 8, 8, 8]
[1, 2, 4, 5, 6, 7, 8, 8, 8]
[1, 2, 4, 5, 6, 7, 8, 8]
>>> 
============== RESTART: C:/Python371/MyP/Ch2_Arrays_Merging.py ==============
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Dixit', 'Sharma', 'is', 'Learning']
>>> 
============== RESTART: C:/Python371/MyP/Ch2_Arrays_Merging.py ==============
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Dixit', 'Sharma', 'is', 'Learning']
Traceback (most recent call last):
  File "C:/Python371/MyP/Ch2_Arrays_Merging.py", line 13, in <module>
    a.extends(b)
AttributeError: 'list' object has no attribute 'extends'
>>> 
============== RESTART: C:/Python371/MyP/Ch2_Arrays_Merging.py ==============
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Dixit', 'Sharma', 'is', 'Learning']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Dixit', 'Sharma', 'is', 'Learning']
>>> 
============== RESTART: C:/Python371/MyP/Ch2_Arrays_Merging.py ==============
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Dixit', 'Sharma', 'is', 'Learning']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Dixit', 'Sharma', 'is', 'Learning']
>>> 
